# Generated by Django 2.1.1 on 2019-06-20 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20190620_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsbbEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=140)),
                ('age', models.IntegerField()),
                ('join_date', models.DateTimeField(default=datetime.datetime(2019, 6, 20, 21, 51, 28, 96896, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='micropost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 21, 51, 28, 96896, tzinfo=utc)),
        ),
    ]
